A__ = [ 1/pi, 0; 0, -1/pi ];
n_y1 = 23;
y1_ = linspace(-5,+5,n_y1); dy1 = mean(diff(y1_));
n_y2 = 24;
y2_ = linspace(-5,+5,n_y2); dy2 = mean(diff(y2_));
[Y1__,Y2__] = ndgrid(y1_,y2_);
dy1dt__ = A__(1,1)*Y1__ + A__(1,2)*Y2__ ;
dy2dt__ = A__(2,1)*Y1__ + A__(2,2)*Y2__ ;
subplot(1,3,1);
quiver(Y1__,Y2__,dy1dt__,dy2dt__);
xlim([-5,+5]); xlabel('y1');
ylim([-5,+5]); ylabel('y2');
axis image;
title('quiver');

ODE_RHS = @(t,Y_) A__* Y_ ;
V__ = ODE_RHS([], [ reshape(Y1__,[1,n_y1*n_y2]) ; reshape(Y2__,[1,n_y1*n_y2]) ] );
V1__ = reshape(V__(1,:),[n_y1,n_y2]);
V2__ = reshape(V__(2,:),[n_y1,n_y2]);
W__ = atan2(V2__,V1__);
U1__ = cos(W__);
U2__ = sin(W__);
r = min(dy1,dy2)*0.45;
Y1_pos__ = Y1__ + r*U1__; Y1_pre__ = Y1__ - r*U1__;
Y2_pos__ = Y2__ + r*U2__; Y2_pre__ = Y2__ - r*U2__;
V_mag__ = sqrt(V1__.^2 + V2__.^2); V_max = max(V_mag__,[],'all');
V_mag_lim_ = [prctile(V_mag__(:),15),prctile(V_mag__(:),85)];
C___ = zeros(n_y1,n_y2,3);
c__ = colormap('cool'); n_c = size(c__,1);
nc_index__ = max(0,min(n_c-1,floor(n_c * (V_mag__ - V_mag_lim_(1))/diff(V_mag_lim_))));
for ny1=0:n_y1-1;
for ny2=0:n_y2-1;
C___(1+ny1,1+ny2,:) = c__(1+nc_index__(1+ny1,1+ny2),:);
end;
end;
subplot(1,3,2);
hold on;
p = patch(transpose([Y1_pre__(:),Y1_pos__(:)]),transpose([Y2_pre__(:),Y2_pos__(:)]),repmat(reshape(C___,[1,n_y1*n_y2,3]),[2,1,1]),'EdgeColor','interp');
hold off;
cb = colorbar();
n_trial = 32; T_max = 15;
for ntrial=0:n_trial-1;
tmp_w = 2*pi*(ntrial+0.5)/n_trial;
Y_ini_ = 2*[cos(tmp_w);sin(tmp_w)];
[t_ode,Y_ode_] = ode23(ODE_RHS,linspace(0,5,64),Y_ini_);
hold on;
plot(Y_ini_(1),Y_ini_(2),'ro');
plot(Y_ode_(:,1),Y_ode_(:,2),'r-','LineWidth',2);
hold off;
end;
xlim([-5,+5]); xlabel('y1');
ylim([-5,+5]); ylabel('y2');
axis image;
title('homebrew');

n_y1 = 64;
y1_ = linspace(-5,+5,n_y1); dy1 = mean(diff(y1_));
n_y2 = 65;
y2_ = linspace(-5,+5,n_y2); dy2 = mean(diff(y2_));
[Y1__,Y2__] = ndgrid(y1_,y2_);
ODE_RHS = @(t,Y_) [ sin(2*pi*Y_(1,:)/4) .* exp(-(Y_(2,:)).^2/(2*2^2)) ; cos(2*pi*Y_(2,:)/4) .* exp(-(Y_(1,:)).^2/(2*4^2)) ]  ;
V__ = ODE_RHS([], [ reshape(Y1__,[1,n_y1*n_y2]) ; reshape(Y2__,[1,n_y1*n_y2]) ] );
V1__ = reshape(V__(1,:),[n_y1,n_y2]);
V2__ = reshape(V__(2,:),[n_y1,n_y2]);
W__ = atan2(V2__,V1__);
U1__ = cos(W__);
U2__ = sin(W__);
r = min(dy1,dy2)*0.45;
Y1_pos__ = Y1__ + r*U1__; Y1_pre__ = Y1__ - r*U1__;
Y2_pos__ = Y2__ + r*U2__; Y2_pre__ = Y2__ - r*U2__;
V_mag__ = sqrt(V1__.^2 + V2__.^2); V_max = max(V_mag__,[],'all');
V_mag_lim_ = [prctile(V_mag__(:),15),prctile(V_mag__(:),85)];
C___ = zeros(n_y1,n_y2,3);
c__ = colormap('copper'); n_c = size(c__,1);
nc_index__ = max(0,min(n_c-1,floor(n_c * (V_mag__ - V_mag_lim_(1))/diff(V_mag_lim_)))); 
for ny1=0:n_y1-1;
for ny2=0:n_y2-1;
C___(1+ny1,1+ny2,:) = c__(1+nc_index__(1+ny1,1+ny2),:);
end;
end;
subplot(1,3,3);
hold on;
p = patch(transpose([Y1_pre__(:),Y1_pos__(:)]),transpose([Y2_pre__(:),Y2_pos__(:)]),repmat(reshape(C___,[1,n_y1*n_y2,3]),[2,1,1]),'EdgeColor','interp');
hold off;
cb = colorbar();
n_trial = 8; T_max = 15;
for ntrial=0:n_trial-1;
tmp_w = 2*pi*(ntrial+0.5)/n_trial;
Y_ini_ = 2*[cos(tmp_w);sin(tmp_w)];
[t_ode,Y_ode_] = ode23(ODE_RHS,linspace(0,5,64),Y_ini_);
hold on;
plot(Y_ini_(1),Y_ini_(2),'ro');
plot(Y_ode_(:,1),Y_ode_(:,2),'r-','LineWidth',2);
hold off;
end;
xlim([-5,+5]); xlabel('y1');
ylim([-5,+5]); ylabel('y2');
axis image;
title('arbitrary');
set(gcf,'Position',1+[0,0,1536,512]);